data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "/root/autodl-tmp/hukangle/Data/MultiviewX"
    batch_size: 1
    num_workers: 8
    use_grid_mask: True
model:
  resolution: [160, 2, 250]  # Y,Z,X
  bounds: [0, 1000, 0, 640, 0, 2]  # xmin,xmax,ymin,ymax,zmin,zmax
  depth: [100, 0, -20]
  num_cameras: 6
  num_ids: 350  # id: 0~349
  gating_threshold: 30000
  use_deformable: True
  use_Temporal: True
  use_new_deformable: True
  use_pre_id_feat: True  # 扩充对比损失样本