data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "/root/autodl-tmp/hukangle/mvdetr/Data/Wildtrack"
    batch_size: 1
    num_workers: 8
    use_grid_mask: True
    history_frames: 0
    new_augmentation: False
model:
  resolution: [120, 2, 360]  # Y,Z,X
  bounds: [0, 1440, 0, 480, 0, 200]  # xmin,xmax,ymin,ymax,zmin,zmax
  depth: [100, 0, 2000]
  learning_rate: 1e-3
  num_cameras: 7
  num_ids: 1201
  useGCD: False
  use_GTE: False
  fusion_type: null
  gnn_type: null
  gnn_layers: 0
  use_deformable: True
  use_Temporal: False

